# Generated by Django 3.2 on 2021-04-17 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid tag name', regex='^[a-zA-Z$][a-zA-Z0-9.@#+-_]*$')]),
        ),
    ]
