# Generated by Django 3.2 on 2021-04-17 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20210417_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='updated_at',
        ),
    ]
