# Generated by Django 3.2 on 2021-04-17 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20210417_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answercomment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='questioncomment',
            name='updated_at',
        ),
    ]
